# filepath: /home/chris/Documents/CRportfolio/netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "https://www.chrisrenshawportfolio.netlify.app"
  to = "https://www.chrisrenshaw.net"
  status = 301
  force = true